### ISSUE TITLE
Auto-provision does not work for a most first domain in the subscription

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#1]
When an instance of the application is set up, a service plan based on the right service template is created and a newly created customer tries to order a service based on the service plan which should provide autoprovision nothing happens - the newly added domain (the first one in the new subscription) are shown in the list as unprotected and there is no any attempt to notify the app about that new domain creation registered in the endpoint logs.

If another domain is added into the subscription from the top above it gets auto protected without any problem, as it should.

**Comment by for93t** [comment]
This behavior has been reproduced by Odin support. The issue occurs due to domain creation before subscription to events starts.

```
apsc.http.log
Mar 25 14:46:11 mn.rashpoa.rforg.apsdemo.org :   IN  0.0.0.0:0  Begin request: "POST /aps/2/application/dns-zone"
Mar 25 14:46:12 mn.rashpoa.rforg.apsdemo.org :   IN  0.0.0.0  [481] "POST /aps/2/application/dns-zone HTTP/1.0"  [0] "200 OK"

app-log
[2016-03-25 11:46:13] Context.INFO: provision: Subscribing to events [] []
```
This behavior will be investigated in Odin internal issue APS-34362 .

**Comment by tonyandrewmeyer** [comment]
Moved to our internal ticket system.
