### ISSUE TITLE
Archiving not activated when Application Counter is increased as part of upgrade

### ISSUE THREAD

**Issue by UH-Nerion** [SpamExperts/aps2-addon#14]
Customer purchase subscription with spamexperts enabled but without archiving enabled.
Later he activate archiving option, it is not getting enabled on spamexpert appliance.

If customer choose archiving during purchase of the subscription, then it is getting enabled.

### Version information
APS 2.0-15

### Steps to replicate

 1. Provision SpamExperts with the archiving 'Application Counter (unit)' set to 0
 1. The archiving product is (correctly) disabled
 1. The customer upgrades their service changing the archiving 'Application Counter' set to 1
 1. This action is not provisioned, archiving remains disabled in SpamExperts

### Actual result
Archiving product is not enabled when the archiving 'Application Counter (unit)' is changed from 0 to 1 after provisioning.

### Expected result
Archiving product should be enabled when the archiving 'Application Counter (unit)' is changed from 0 to 1 after provisioning.

### Other notes
Information requested from Odin: [APS [#2076135](https://support.apsstandard.org/SelfService/Display.html?id=2076135)]

**Comment by alexkiro** [comment]
Hello, 

Thank you for contacting us. 

For faster response time to your questions please contact the support team directly by sending an email to support@spamexperts.com. If you are using the SpamExperts services from a reseller and not from SpamExperts directly, you need to contact your provider. If they cannot assist, they need to contact the SpamExperts support team for you. 

We would kindly ask you to provide a detailed explanation as to what the issue is and what you are trying to achieve so the support team can investigate this faster for you.

**Comment by dreasvandonselaar** [comment]
As this design was originally provided by Odin, a ticket has been created requesting for more information [APS #2076135].

**Comment by dreasvandonselaar** [comment]
The customer indicated they are providing the service as upsell ('Buy more resources' button), which according to Odin is supposed to trigger 'http://parallels.com/aps/events/pa/subscription/limits/changed' event.

**Comment by dreasvandonselaar** [comment]
Another suggestion from Odin:
```
Please consider if "SE Archiving" resource can be configured as "Application Service" so that the upgrade order can increase the resource limit.
```

And feedback on that from the customer:
```
As you don't use the resource „SE Archiving“ as real counter resource, nothing is counted here. So changing this should not break other APS2 deployments? Also you can add an additional resource (for example „SE EnableArchiving“) as Application Service resource. This should not affect other customers, because the old resource is still available, and you just add a new resource from type „Application Service“.
```

We'll need to implement whatever seems most consistent.

**Comment by catalinDonici** [comment]
@for93t, it seems that if the `Unlimited` value is used for the Incoming and Outgoing these products will be disabled when doing an upgrade. 

### Steps to replicate:
- Provision SpamExperts with the incoming 'Application Counter (unit)' set to Unlimited 
- Provision SpamExperts with the outgoing 'Application Counter (unit)' set to Unlimited 
- Provision SpamExperts with the archiving 'Application Counter (unit)' set to 0
  - The incoming product is enabled
  - The archiving product is enabled
  - The archiving product is (correctly) disabled
- The customer upgrades their service changing the archiving 'Application Counter' set to 1

### Actual result:
- The archive is correctly provisioned now
- The incoming is disabled
- The outgoing is disabled 

### Expected result
- Incoming and Outgoing products should remain enabled when the archiving 'Application Counter (unit)' is changed from 0 to 1 after provisioning.

**Comment by catalinDonici** [comment]
Verified.
