### ISSUE TITLE
Protection status can be shown incorrectly for users with multiple subscriptions

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#2]
It can be the case when a customer with 2 or more subscriptions protects their domains using different subscription and then switches active subscription the domains which have not been protected under active subscription re shown as unprotected, while they actually are protected.

This happens because for each subscription a new sub-admin in SpamExperts control panel is created and these new accounts' credentials are used for protection. And due to security reason accounts at the same level cannot retrieve information about other accounts' domains. That's why one subscription cannot pull information about domains of another accounts.

The solution here can be to just hide the domains in the SpamExperts application which don't belong to active subscription - it would make the whole behavior cleaner for end-users.

**Comment by tonyandrewmeyer** [comment]
Moved to our internal ticket system.
