### ISSUE TITLE
Protection failed for domain

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/aps2-addon#22]
A client is trying to protect a domain however he's recieving an error. Logs attached

WHMCS ticket #172034

**Comment by for93t** [comment]
> The domain didn't belong to any other admin as he was able to manually add it.

@alexkiro, does it mean that the domain already was present in the spamfilter at the moment of the protection attempt but did not belong to any of the server's admin?

**Comment by for93t** [comment]
We really miss debug logs for the case so it's quite tricky to figure out what went wrong in the client's environment.

**Comment by alexkiro** [comment]
> We really miss debug logs for the case so it's quite tricky to figure out what went wrong in the client's environment.

Closing this for now.
