### ISSUE TITLE
Package failing to list correct domains for provider subscription 1

### ISSUE THREAD

**Issue by dreasvandonselaar** [SpamExperts/aps2-addon#24]
### Version information

APS 2.0-15

### Steps to replicate

In odin service automation there is a subscription with ID 1. This subscription is reserved for the hosting provider. It is available in hosting CP of Odin service automation. Accessing this subscription from the APS2 package doesn't work, as our APS doesn't seem to support this special subscription with ID 1. It does list some domains, but not the correct ones that are supposed to be listed.

Odin indicated:
```
The issue of why other service users from other customers are displayed on Hosting CP (Provider CP) for Spamexperts are due to the design of the APS applications, which do not implement proper filtering.
Since the APS is packaged by Spamexperts, please contact Spamexperts team with the description of this problem
```
More details are provided in an internal email thread "Modification on APS2 to be used with provider subscription 1".

### Actual result

Wrong domains listed when accessing the subscriber 1 account in OA.

### Expected result

Correct subscriber 1 domains showing.

### Other notes

![unbenannt 8](https://cloud.githubusercontent.com/assets/4503663/24909626/f244f520-1ec4-11e7-9edc-13dd790f941a.PNG)

**Comment by LaurentiuTeodorescu** [comment]
On a fresh CloudBlue 20.5 instance, the first subscription has ID: 1000001, thus closing this as out of date.
