### ISSUE TITLE
Test the APS2 application compatibility with OSA 7.1

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#30]
So far we used to submit our APS 2 application claiming compatibility with OSA 6 but it is reaching it's EOL (OSA 6.0.x is nearing its End Of Life at 01.08.2017). Therefore it is suggested to develop and certify packages for OSA 7.1. So we need to test our application on the latest version of the platform to see if there are compatibility issues and resubmit the package.

### Version information

2.0-18

### Acceptance criteria 

 - [ ] We need regression tests on this 
 - [ ] Any problems that we find and we need to fix them

### Other notes 

 -

**Comment by lorentina** [comment]
White testing, I found the following issues:
1. If there are 2 protected domains using 2 separate subscriptions, protecting one of them using another subscription leads to an error when trying to unprotect and protect it again using its initial subscription.

2. If domain is removed from Spampanel (using Spampanel): notice that `Protect` and `Unprotect` buttons do not change the `Status` of the domain, but they activate/de-activate the `Login` button (although the button will not do anything, as there is an error shown upon login)

**Comment by alexkiro** [comment]
@for93t and @lorentina please give an update here this is now overdue.

**Comment by for93t** [comment]
@lorentina, about the issues you have mentioned.

I'm unable to reproduce the 1st one on `http://ap2.spamexperts.apsdemo.org:8080/` - there are 2 subscription - `#7 Antispam for issue #30 one` & `#8 Antispam for issue #30 two`  - and it is possible to move domains between those without any problem.

I also don't fully understand the 2nd one - it's also not reproducible on the mentioned sandbox. However it there is an issue I tend to think that it is not related to OSA version thus unrelated here and needs a separate issue with detailed steps to reproduce the problem. Or (ideally) a sandbox there the reproducible problem can be seen by anyone.

**Comment by lorentina** [comment]
Verified again on a clean environment. Since no major issues were encountered, this will be sent for deployment.

**Comment by alexkiro** [comment]
Approved by Odin.
