### ISSUE TITLE
Aps provisioning issue: Incoming and Archiving active when they should not be active

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/aps2-addon#33]
### Version information

Spamexpert version is 2.0-16
OSA version is 7.1

### Steps to replicate

 1. configure a plan with autoprotect,
 2. set autoprotect domain as 0,
 3. try to protect domains

### Actual result

all domains are still getting protected when subscription provisioned.

### Expected result

domains should be added to the interface without the Incoming and Archiving products.

**Comment by lorentina** [comment]
I was not able to reproduce the issue, more details about the service plan/service template are needed.
Notice domains do not appear protected by default.

**Comment by for93t** [comment]
I have the environment set up on `http://ap2.spamexperts.apsdemo.org:8080/`.

The [fix](https://github.com/SpamExperts/aps2-addon/commit/6b68e0fa042ef1af495d0c99c812adb96f1adafe) has been reverted on that sandbox.

The steps to reproduce the issue are:

- Log in as `admin` on the sandbox
- Go to `Subscriptions` -> `Antispam for issue #33` -> `Resources` tab
- Notice that the `Antispam Autoprotect Domains` resource is set to `0`
- Open an SSH session to `endpoint.ap2.spamexperts.apsdemo.org`
- Run `tail -f /var/www/html/se/logs/app-log-2017-09-10`
- Go back to the OSA, go to `Customers` -> Customer ID=4 -> Login As
- Got to `Domain` and `Add new domain`
- Get back to the SSH window and notice an entry saying something like `Context.INFO: context::onDomainAvailable: auto_protect_domain is enabled;...` which is not correct
- With the fix applied the log record says something like `Context.INFO: context::onDomainAvailable: auto_protect_domain is disabled;...`

**Comment by lorentina** [comment]
Verified.
