### ISSUE TITLE
Updating the domain limit for an admin in APS does not reflect in SE control panel

### ISSUE THREAD

**Issue by VicSpam01** [SpamExperts/aps2-addon#35]
### Version information
2.0

### Steps to replicate

 1. Add and admin
2. Update the domain limit
3. Domain limit is updated in APS but unchanged for the admin in the Control panel

### Actual result
OA upgrades / SE doesn't

### Expected result
SE should match OA

**Comment by for93t** [comment]
The APS 2 application works fine. The actual (Spampanel API) issue has been pinpointed and fixed. Internal ticket ID for reference is `#33691`.
