### ISSUE TITLE
Application sets incorrect usage values in OSA every night

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#38]
### Version information
OSA Version 7.3
SE APS 2.0 application v2.0-19

### Steps to replicate

A client informed us that the APS package is no longer working with latest OSA Version 7.3. The APS package has a bug that sets incorrect values in OSA every night which makes SpamExperts unusable.

### Actual result

All usages (incoming/outgoing/archiving) are reported as zeros.

### Expected result

Real usages to be reported.

**Comment by for93t** [comment]
As discussed internally, I'm closing this as fixed.

**Comment by tonyandrewmeyer** [comment]
Tickets may not be closed until the changes have been published.

**Comment by for93t** [comment]
Status of APS package "SpamExperts-2.0-20" has been changed to "Published".
