### ISSUE TITLE
Internal error: APSC: Upgrade to ver. 2.0-20

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/aps2-addon#40]
### Version information

2.0.15
### Steps to replicate

 1. Client tries to upgrade the resource

### Actual result
Internal error: APSC: Upgrade to ver. 2.0-20 : resource 488d6a59-19c9-43bc-90fd-b6d95720234b of type 'service' (http://aps.spamexperts.com/app/service/1.4) for APS application 'SpamExperts-2.0-20' : 'ignoreRemoteDomains': property is required.

### Expected result
Upgrade should finish with no errors

### Other notes
Whmcs: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=197762

**Comment by for93t** [comment]
@adaivan can you please advice the client to upgrade to v2.0-19 first and then to the latest one? The error should not appear if the upgrades are executed in the right order.

**Comment by LaurentiuTeodorescu** [comment]
I'll close this as out of date.
