### ISSUE TITLE
PHPUnit package should not be deployed

### ISSUE THREAD

**Issue by catalinDonici** [SpamExperts/aps2-addon#44]
### Version information

2.0.21

### Steps to replicate

 1. Install the latest package on a testing APS sandbox

### Actual result

`Please note that the support for PHPUnit 4 by the PHPUnit Project ended on February 3, 2017. Also note that PHP 5.3, PHP 5.4, and PHP 5.5 are no longer supported by the PHP Project.`

### Expected result

PHPUnit package should not be deployed

**Comment by emiliangrecu** [comment]
Verified fix.
