### ISSUE TITLE
Adjust aps2-addon so it's compatible with Odin Automation Premium 8.0

### ISSUE THREAD

**Issue by donici** [SpamExperts/aps2-addon#47]
We need to ask Odin first to provide a sandbox that has the Odin Automation Premium 8.0. 

After that we need to test the addon and fix any issues that we found.

**Comment by tonyandrewmeyer** [comment]
They previously told us that they don't do sandboxes any more, right?

```
Indeed, APS Developer portal will no longer be developed and supported, no new sandboxes will be provided. Soon there will be a notification on the portal also.

Providers willing to build their integration with Odin should switch to CloudConnect solution:

https://vendor.connect.cloudblue.com/login
https://www.cloudblue.com/platform/

Please consider this for future.
```

**Comment by ili101** [comment]
I have opened a support ticket and they redirected me to here, and here I see that you don't even have a working development environment? No. Odin don't provide sandboxes any more.
Odin Automation 7.4 EOL is in 24 days and it looks like we are going we be stuck with a broken APS! This is ridicules.
We have upgraded our LAB environment and the "SE Domain" resource cannot be provisioned.
 
Did you start working on it? what is the status?

**Comment by UH-Nerion** [comment]
Hello,

is this project dead?
SpamExperts is still working with OSA 8.2
But how long?

**Comment by ili101** [comment]
Congratulation everyone! 🌹
We are officially paying for a dead product
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉🎉 🎉 

:poop:

**Comment by UH-Nerion** [comment]
Hello,

we can give you access to a sandbox if needed for developing it to OA 8.3

Thanks

**Comment by LaurentiuTeodorescu** [comment]
This was fixed in https://github.com/SpamExperts/aps2-addon/pull/49 
And Updated for CloudBlue 20.4 and 20.5 in https://github.com/SpamExperts/aps2-addon/pull/51/
