### ISSUE TITLE
APS2.0 addon fails to add the correct destination when protecting domains

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/aps2-addon#48]
### Version information
7.4 platform 
APS 2.0-21 

### Steps to replicate

 1. install addon on 7.4 platform
2.  create a ST and SP
3. order it
4, add a domain
5. Use the protect option 

### Actual result

Fails to add the correct destination + mx records are not correctly set

### Expected result

Domain should be added with the correct destination

### Other notes

CodeBlue investigated this and found the issue with the variable $SEMXs in context.php within the replaceMXRecords method is not filled with the mx records being set in the APS's configuration screen (mx1 to mx4) .. these come from $this->mx, but that property is empty and I can't find a place where it's being properly set when the APS wants to set MX records. There's one place, but that method getServiceMXRecords isn't even properly working.

ticket: 998170

**Comment by marknl** [comment]
How can such a critical bug be prioritized as "normal". This affects the working of this APS completely. This has been reported by me to SE support as well, they don't really seem to be impressed and don't care. I guess Solarwinds has other priorities.

What I did to somewhat fix this, is call `$this->mx = $this->getServiceMXRecords();` in all function where `$this->mx` is needed.

**Comment by LaurentiuTeodorescu** [comment]
Fixed in https://github.com/SpamExperts/aps2-addon/pull/51/
